#!/bin/bash

# Define the path to the torrc file
TORRC_PATH="./torrc"

# Define the HiddenServiceDir relative to the current directory
HIDDEN_SERVICE_DIR="$(pwd)/HiddenServiceDir"

# Ensure the HiddenServiceDir directory exists, if not, create it
if [ ! -d "$HIDDEN_SERVICE_DIR" ]; then
    echo "Creating $HIDDEN_SERVICE_DIR directory..."
    mkdir -p "$HIDDEN_SERVICE_DIR"
    # Set the directory permissions to 700 as required by Tor
    chmod 700 "$HIDDEN_SERVICE_DIR"
else
    # If the directory already exists, ensure it has the correct permissions
    chmod 700 "$HIDDEN_SERVICE_DIR"
fi

# Reset the torrc file and write the minimal configuration
echo "Resetting and updating $TORRC_PATH with minimal configuration..."

# Write the configuration directly, overwriting any existing file
cat <<EOT > "$TORRC_PATH"
# Tor configuration generated by script
HiddenServiceDir $HIDDEN_SERVICE_DIR
HiddenServicePort 80 127.0.0.1:80
EOT

echo "Configuration updated successfully."
